name: Comparar Token

on:
  push:

jobs:
  comprobar:
    runs-on: self-hosted

    steps:
      - name: Comparar token
        shell: pwsh
        run: |
          if ("${{ secrets.DEV_TOKEN }}" -eq $env:LOCAL_DEV_TOKEN) {
            Write-Output "Coinciden"
          } else {
            Write-Output "No coinciden"
            exit 1
          }