name: Comparar Token

on:
  push:

jobs:
  comprobar:
    runs-on: self-hosted

    steps:
      - name: Comparar token
        run: |
          if ($env:LOCAL_DEV_TOKEN -eq "${{ secrets.DEV_TOKEN }}") {
            Write-Output "Coinciden"
          } else {
            Write-Output "No coinciden"
            exit 1
          }